# Generated by Django 5.2.7 on 2025-10-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.CharField(help_text='格式：feature-xxx', max_length=64, primary_key=True, serialize=False, verbose_name='特性唯一ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='特性名称')),
                ('module_id', models.CharField(help_text='外键：tb_module.id', max_length=64, verbose_name='所属模块ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='特性描述')),
                ('case_count', models.IntegerField(default=0, verbose_name='关联用例数')),
                ('creator', models.CharField(help_text='关联tb_user.id', max_length=64, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '特性信息',
                'verbose_name_plural': '特性信息',
                'db_table': 'tb_feature',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['module_id'], name='idx_module'), models.Index(fields=['creator'], name='feature_idx_creator')],
            },
        ),
        migrations.CreateModel(
            name='FeatureTestCaseRelation',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.CharField(help_text='格式：relation-xxx', max_length=64, primary_key=True, serialize=False, verbose_name='关联ID')),
                ('feature_id', models.CharField(help_text='外键：tb_feature.id', max_length=64, verbose_name='特性ID')),
                ('test_case_id', models.CharField(help_text='外键：tb_test_case.id', max_length=64, verbose_name='测试用例ID')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序索引')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主用例')),
                ('creator', models.CharField(help_text='关联tb_user.id', max_length=64, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '特性-测试用例关联',
                'verbose_name_plural': '特性-测试用例关联',
                'db_table': 'tb_feature_testcase_relation',
                'indexes': [models.Index(fields=['feature_id'], name='idx_feature_relation'), models.Index(fields=['test_case_id'], name='idx_testcase_relation'), models.Index(fields=['is_primary'], name='idx_is_primary')],
                'unique_together': {('feature_id', 'test_case_id')},
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.CharField(help_text='格式：case-xxx', max_length=64, primary_key=True, serialize=False, verbose_name='用例唯一ID')),
                ('case_id', models.CharField(max_length=50, unique=True, verbose_name='用例ID（系统内部标识）')),
                ('case_name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('feature_id', models.CharField(help_text='外键：tb_feature.id', max_length=64, verbose_name='所属特性ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用例描述')),
                ('pre_condition', models.TextField(verbose_name='前置条件')),
                ('steps', models.TextField(verbose_name='执行步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('script_path', models.CharField(help_text='Docker 数据卷内路径', max_length=200, verbose_name='用例脚本路径')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('draft', '草稿')], default='active', max_length=20, verbose_name='用例状态')),
                ('sync_time', models.DateTimeField(null=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'tb_test_case',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['feature_id'], name='idx_feature'), models.Index(fields=['status'], name='idx_status')],
            },
        ),
    ]
