# Generated by Django 5.2.7 on 2025-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_testcase', '0002_update_existing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='creator',
            field=models.CharField(default='test', help_text='关联tb_user.id', max_length=64, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='priority',
            field=models.IntegerField(default=50, help_text='1-100，数字越小优先级越高', verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_phase',
            field=models.CharField(choices=[('unit', '单元测试'), ('integration', '集成测试'), ('system', '系统测试'), ('acceptance', '验收测试')], default='system', max_length=20, verbose_name='测试阶段'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('manual', '手动测试'), ('automated', '自动化测试'), ('semi_automated', '半自动化测试')], default='manual', max_length=20, verbose_name='测试类型'),
        ),
    ]
