# Generated by Django 5.2.7 on 2025-10-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
