# Generated by Django 5.2.7 on 2025-10-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('operation_desc', models.TextField(blank=True, null=True, verbose_name='操作描述')),
                ('operated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('module_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='模块名称')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='对象ID')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='旧数据')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='新数据')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'tb_audit_log',
                'ordering': ['-operated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON')], default='string', max_length=20, verbose_name='类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否生效')),
                ('created_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'tb_system_config',
            },
        ),
    ]
