# Generated by Django 5.2.7 on 2025-10-08 15:47

import django.db.models.deletion
import execution_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('env_manager', '0001_initial'),
        ('test_suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.CharField(default=execution_manager.models.generate_task_id, max_length=64, primary_key=True, serialize=False, verbose_name='任务唯一ID')),
                ('package_info', models.TextField(verbose_name='包信息')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '运行中'), ('paused', '已暂停'), ('terminated', '已终止'), ('success', '执行成功'), ('failed', '执行失败')], default='pending', max_length=32, verbose_name='任务状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('executor', models.CharField(max_length=64, verbose_name='执行人')),
                ('total_case', models.IntegerField(default=0, verbose_name='总用例数')),
                ('success_case', models.IntegerField(default=0, verbose_name='成功用例数')),
                ('failed_case', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('env_id', models.ForeignKey(db_column='env_id', on_delete=django.db.models.deletion.CASCADE, to='env_manager.environment', verbose_name='关联环境ID')),
                ('suite_id', models.ForeignKey(db_column='suite_id', on_delete=django.db.models.deletion.CASCADE, to='test_suite.testsuite', verbose_name='关联测试套ID')),
            ],
            options={
                'verbose_name': '任务执行信息',
                'verbose_name_plural': '任务执行信息',
                'db_table': 'tb_execution_task',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['suite_id'], name='execution_idx_suite'), models.Index(fields=['env_id'], name='execution_idx_env'), models.Index(fields=['status'], name='execution_idx_status'), models.Index(fields=['start_time', 'end_time'], name='execution_idx_time')],
            },
        ),
    ]
